image: rappdw/docker-java-python


stages:
- build
- publish
- deploy

build:
  stage: build
  script:
  - ./gradlew clean test

publish:
  stage: publish
  artifacts:
    paths:
    - ./build/libs/*
  script:
  - ./gradlew fatJar

deploy:
  stage: deploy
  script:
  - pip install awscli
  - apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get install zip
  - apt-get install zip
  - cd ./build/libs
  - zip -X -r ../../norris.zip *
  - cd ../..
  - aws lambda update-function-code --function-name ChuckFactor --zip-file fileb://norris.zip